repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
        - id: trailing-whitespace  # убирает лишние пробелы
        - id: check-added-large-files  # проверяет тяжелые файлы на изменения
        - id: end-of-file-fixer  # добавляет пустую строку в конце файла
        - id: check-yaml  # проверяет синтаксис .yaml файлов
        - id: check-json  # проверяет синтаксис .json файлов
        - id: check-case-conflict  # проверяет файлы, которые могут конфликтовать в файловых системах без учета регистра.
        - id: check-merge-conflict  # проверяет файлы, содержащие конфликтные строки слияния.

#Сортировка испортов в проекте
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        exclude: __init__.py */env.py
        args: [--profile, black, --filter-files]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py39-plus]

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.1
    hooks:
    -   id: autopep8

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: ["--ignore=F821", "--extend-exclude=*/__init__.py,*/env.py", "--max-line-length=120"]


-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        additional_dependencies: [types-redis==4.4.0.4]
        args: [--no-strict-optional, --ignore-missing-imports, --config-file=mypy.ini]


    # Форматирует код под PEP8 c помощью black
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        language_version: python3.9
