version: '3.9'

services:

  test_menu_app:
    container_name: test_menu_app
    build:
      context: .
      dockerfile: DockerfileTest
    env_file:
      - .env.tests
    command: "pytest -vv"
    networks:
      - menuapp_menu_network

networks:
  menuapp_menu_network:
    external: true

