version: '3.9'

services:

  test_menu_app:
    container_name: test_menu_app
    build:
      context: .
      dockerfile: DockerfileTest
    env_file:
      - .env.dev
    command: "pytest -vv"
    networks:
      - menu_network
    depends_on:
      menu_postgres_db:
        condition: service_healthy

networks:
  menu_network:
