version: '3.9'

services:

  test_menu_app:
    container_name: test_menu_app
    build:
      context: .
      dockerfile: DockerfileTest
    env_file:
      - .env.tests
    command: "pytest -vv"
    networks:
      - test_menu_network
    depends_on:
      test_menu_postgres_db:
        condition: service_healthy
      test_menu_redis:
        condition: service_healthy

  test_menu_postgres_db:
    container_name: test_menu_postgres_db
    image: postgres:15.1-alpine
    volumes:
      - postgres_tests_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    ports:
      - "5433:5432"
    networks:
      - test_menu_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 20s
      retries: 100

  test_menu_redis:
    container_name: test_menu_redis
    image: redis:latest
    expose:
      - 6379
    ports:
      - "6380:6379"
    networks:
      - test_menu_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 20s
      retries: 100

networks:
  test_menu_network:

volumes:
  postgres_tests_data:
