version: '3.9'

services:
  menu_app:
    container_name: menu_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    networks:
      - menu_network
    ports:
      - "8000:8000"
    depends_on:
      menu_postgres_db:
        condition: service_healthy

  menu_postgres_db:
    container_name: menu_postgres_db
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - menu_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 20s
      retries: 100

networks:
  menu_network:

volumes:
  postgres_data: